# Generated by Django 5.2b1 on 2025-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
