# Generated by Django 5.2b1 on 2025-06-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_api', '0003_create_initial_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Vĩ độ tại thời điểm chấm công', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Kinh độ tại thời điểm chấm công', null=True),
        ),
    ]
